# Generated by Django 5.1.6 on 2025-03-29 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the specialization (e.g., Cardiology, Neurology)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL for the specialization', max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this specialization', null=True)),
                ('department', models.CharField(blank=True, help_text='Department under which this specialization falls', max_length=100, null=True)),
                ('is_surgical', models.BooleanField(default=False, help_text='Does this specialization involve surgery?')),
                ('is_primary_care', models.BooleanField(default=False, help_text='Is this a primary care specialization?')),
                ('icon', models.ImageField(blank=True, help_text='Icon or logo for this specialization', null=True, upload_to='specialization_icons/')),
                ('qualifications', models.TextField(blank=True, help_text='Required qualifications for doctors in this specialization', null=True)),
                ('average_consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Typical fee for consultation', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this specialization currently active?')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='management__name_f8b98f_idx')],
            },
        ),
    ]
