# Generated by Django 5.1.6 on 2025-04-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient'),
        ),
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_slots', to='profiles.doctor'),
        ),
        migrations.AddField(
            model_name='clinicalattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='specialization',
            index=models.Index(fields=['display_order', 'name'], name='management__display_e35569_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_time', '-priority'], name='management__schedul_b7d98c_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('doctor', 'scheduled_time'), name='unique_doctor_appointment_time'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time', 'end_time'), name='unique_doctor_time_slot'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddIndex(
            model_name='clinicalattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='management__content_876956_idx'),
        ),
    ]
