# Generated by Django 5.1.6 on 2025-04-06 20:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_time',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='management__schedul_b7d98c_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', '-priority'], name='management__schedul_7fd336_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('doctor', 'scheduled_date'), name='unique_doctor_appointment_time'),
        ),
    ]
