# Generated by Django 5.1.6 on 2025-04-08 17:25

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_appointment_unique_doctor_appointment_time_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalattachment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='management.appointment'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='management.clinicalattachment')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 8))])),
                ('end_datetime', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 8))])),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.doctor')),
            ],
            options={
                'verbose_name': 'Time Off',
                'verbose_name_plural': 'Time Offs',
            },
        ),
    ]
