# Generated by Django 5.1.6 on 2025-04-06 14:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgcrypto.fields
import profiles.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system_admin', 'System Administrator'), ('clinician', 'Licensed Clinician'), ('patient', 'Patient'), ('nurse', 'Registered Nurse'), ('support', 'Support Staff')], db_index=True, default='patient', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Verification'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20)),
                ('address', models.JSONField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='International format: +[country code][number]', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=20)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Healthcare User',
                'verbose_name_plural': 'Healthcare Users',
                'permissions': [('view_full_profile', 'Can view complete user profile'), ('emergency_access', 'Has emergency access privileges')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to='profiles.healthcareuser')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('known_allergies', models.JSONField(default=list, help_text='List of known allergies and reactions')),
                ('permanent_medications', models.JSONField(default=list, help_text='Long-term medication regimen')),
                ('emergency_contacts', models.JSONField(default=list, help_text='Emergency contacts')),
                ('primary_insurance', pgcrypto.fields.EncryptedTextField(blank=True, charset='utf-8', check_armor=True, cipher='aes', help_text='Encrypted insurance policy details', null=True, versioned=False)),
            ],
            options={
                'verbose_name': 'Patient Health Profile',
                'verbose_name_plural': 'Patient Health Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('image', models.ImageField(upload_to='profile_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), profiles.models.validate_image_size])),
                ('thumbnail', models.ImageField(blank=True, upload_to='profile_thumbs/%Y/%m/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
            },
        ),
        migrations.AddField(
            model_name='healthcareuser',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_image', to='profiles.profileimage'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clinician_profile', serialize=False, to='profiles.healthcareuser')),
                ('license_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('medical_license', pgcrypto.fields.EncryptedCharField(charset='utf-8', check_armor=True, cipher='aes', help_text='Encrypted medical license number', versioned=False)),
                ('license_jurisdiction', models.CharField(help_text='Issuing authority for medical license', max_length=100)),
                ('certifications', models.JSONField(default=dict, help_text='Board certifications and qualifications')),
                ('accepting_new_patients', models.BooleanField(default=True)),
                ('emergency_availability', models.BooleanField(default=False)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('fees', models.PositiveIntegerField(blank=True, null=True)),
                ('specializations', models.ManyToManyField(related_name='doctors', to='management.specialization')),
            ],
            options={
                'verbose_name': 'Clinician Profile',
                'verbose_name_plural': 'Clinician Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='healthcareuser',
            index=models.Index(fields=['username', 'email'], name='profiles_he_usernam_745692_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareuser',
            index=models.Index(fields=['role'], name='profiles_he_role_f2589c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareuser',
            index=models.Index(fields=['status'], name='profiles_he_status_4a2d74_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcareuser',
            index=models.Index(fields=['date_of_birth', 'gender'], name='profiles_he_date_of_459fb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('medical_license', 'license_jurisdiction'), name='unique_medical_license'),
        ),
    ]
